language: php
services:
    - docker
php:
    - 7.0
sudo: false
before_install:
    - composer install
    - chmod +x install-phalcon.sh
    - ./install-phalcon.sh
script: ./src/Framework/vendor/bin/phpunit -c ./tests
    

